export const consultingServicesByLocale = {
  zh: {
    sectionLabel: "商業顧問服務",
    sectionMeta: "五個專業方向",
    intro: "評估既有品牌規範、營運流程與技術環境，釐清各階段的目標、協作分工及執行優先順序。",
    labels: { situations: "適用需求", scope: "服務範圍", deliverables: "規劃成果", execution: "後續執行", consult: "聯絡我們" },
    processTitle: "顧問合作流程",
    process: ["現況盤點", "目標確認", "策略規劃", "執行協作", "成效檢視"],
    services: [
      { id: "systems-consulting", shortLabel: "資訊系統", title: "資訊系統", summary: "從需求與流程盤點到客製開發，整合系統、資料與權限，支援日常作業及後續維運。", situations: ["準備導入或汰換 ERP、CRM、WMS","既有系統分散，流程與資料難以串接"], scope: [{"title":"流程與系統規劃","description":"盤點現行作業、使用角色與既有工具，整理功能需求、資料流向及導入優先順序。"},{"title":"客製開發與系統串接","description":"開發管理系統與應用、串接既有平台，規劃 AI 輔助、自動化、儀表板與異常提醒。"},{"title":"資料與權限設計","description":"整合資料來源與欄位，規劃資料治理、角色權限、存取紀錄與資訊安全需求。"},{"title":"導入與維運交接","description":"規劃測試、驗收、部署、備份及操作交接，明確約定原始碼、主機與後續維護範圍。"}], deliverables: ["需求分析","系統架構圖","導入藍圖"], execution: "可依規劃執行客製系統開發、既有系統整合與專案協作。" },
      { id: "digital-integration", shortLabel: "數位整合", title: "數位整合", summary: "建置品牌網站、電商與會員功能，串接金流、物流及內部系統，讓網站與日常營運順暢銜接。", situations: ["不同工具之間需要重複輸入或人工彙整資料","網站、金流、物流與內部系統各自運作"], scope: [{"title":"品牌網站與多語建置","description":"規劃內容架構、頁面與管理功能，兼顧裝置相容、品牌呈現及日常內容更新。"},{"title":"電商、會員與預約","description":"依服務流程建置商品、交易、會員或預約功能，確認付款、通知及後續作業的串接需求。"},{"title":"第三方服務與資料串接","description":"盤點金流、物流、CRM、ERP 等平台介面，整理資料交換、更新責任及異常處理方式。"},{"title":"作業自動化與交接","description":"將已確認的重複作業納入自動化，規劃整合測試、資料移轉、上線及操作交接。"}], deliverables: ["整合架構圖","串接清單","執行優先序"], execution: "可依規劃建置網站、電商、會員功能，以及金流、物流與自動化串接。" },
      { id: "visual-design", shortLabel: "視覺設計", title: "視覺設計", summary: "提供品牌識別、網站與介面視覺、行銷素材及應用規範，讓不同接觸點維持清楚一致的品牌表現。", situations: ["品牌視覺缺乏一致性","數位介面資訊層級不清楚"], scope: [{"title":"品牌識別與應用","description":"檢視既有品牌或規劃識別方向，製作約定的標誌、色彩、字體及品牌應用。"},{"title":"網站與介面視覺","description":"整理資訊層級與使用情境，規劃頁面、操作介面及元件的視覺呈現。"},{"title":"行銷與印刷素材","description":"依通路需求製作社群、廣告、簡報、型錄及印刷版型，確認尺寸與輸出規格。"},{"title":"設計規範與交接","description":"整理版型與素材使用方式，約定可編輯檔、輸出格式及字型、圖庫等授權條件。"}], deliverables: ["視覺方向","設計規範","改善清單"], execution: "可依規劃製作品牌識別、介面、網站視覺與行銷素材。" },
      { id: "international-marketing", shortLabel: "國際行銷", title: "國際行銷", summary: "依目標市場規劃品牌定位、多語內容、搜尋與廣告通路，串聯網站及成效追蹤，支援海外市場經營。", situations: ["準備進入海外市場","已有多語內容，希望改善海外客戶的洽詢與購買流程"], scope: [{"title":"市場與受眾定位","description":"依產品、客群、競爭條件與資源評估目標市場，整理市場進入方向與通路分工。"},{"title":"多語內容與搜尋","description":"規劃在地化內容、搜尋用語與網站架構，確認翻譯、在地審核及持續更新的責任。"},{"title":"行銷素材與廣告執行","description":"依約定製作內容與廣告素材、管理投放通路，分別確認帳號權限、媒體預算及服務費。"},{"title":"成效追蹤與調整","description":"依營運目標規劃洽詢、轉換及其他可查核指標，提供報表與改善建議，實際成效依市場條件評估。"}], deliverables: ["市場進入策略","內容方向","執行計畫"], execution: "可依規劃製作多語網站與廣告素材，並執行 SEO 及海外行銷。" },
      { id: "international-finance", shortLabel: "國際金融", title: "國際金融", summary: "結合資訊技術與跨境法律、稅務、金融專業資源，協助企業與家族整理資產、評估交易及規劃跨國布局，讓決策建立在可查核的資訊上。", situations: ["企業準備跨國投資、資金媒合或跨境交易","資產分布多地，需要統整持有關係與財務資訊","家族成員具不同國籍或居住地，需要傳承與信託規劃協作","投資或合作前，需要查核背景、資金及退出條件"], scope: [{"title":"跨國資金媒合","description":"整理資金需求、對接專業資源與協調合作條件"},{"title":"跨境資產盤點","description":"彙整資產、負債、持有架構與相關文件"},{"title":"背景調查與驗資協作","description":"查核公開及合法授權資料、資金證明與文件真偽"},{"title":"跨境稅務與金流規劃協作","description":"串聯律師、稅務及金融專業人員，整理申報與交易需求"},{"title":"信託與傳承規劃協作","description":"整理受益安排、跨境繼承需求與設立作業"},{"title":"企業跨境架構","description":"協同專業團隊評估公司、股權與投資架構"},{"title":"投資風險與退出評估","description":"釐清交易條件、資金流向、退出機制與待確認風險"},{"title":"家族辦公室與資產規劃系統","description":"整合資產資料、文件、權限、報表及協作流程"}], deliverables: ["跨境需求與資產清冊、持有關係圖","背景調查與驗資資料彙整、待查核事項","專業團隊分工、規劃議題與執行順序","交易風險、退出條件及決策資訊清單","資產管理與家族辦公室系統建置藍圖"], execution: "由 ESTIGINTO 負責資訊整合、系統建置與跨專業協作；法律、稅務、信託及金融事項，依需求串聯相關專業團隊共同評估與執行。" },
    ],
  },
  en: {
    sectionLabel: "Business Consulting", sectionMeta: "Five advisory practices", intro: "We review brand standards, operating processes, and technical environments to define priorities, responsibilities, and a practical implementation plan.",
    labels: { situations: "Best for", scope: "Service scope", deliverables: "Deliverables", execution: "Execution support", consult: "Discuss a project" }, processTitle: "How we work", process: ["Current state", "Goals", "Strategy", "Execution", "Review"],
    services: [
      { id: "systems-consulting", shortLabel: "Information Systems", title: "Information Systems", summary: "Plan and build systems around your workflows, data, and access needs, with integration, rollout, and operational handover.", situations: ["Planning an ERP, CRM, or WMS rollout","Disconnected systems and manual handoffs"], scope: [{"title":"Workflow and system planning","description":"Review operations, user roles, and existing tools to define features, data flows, and rollout priorities."},{"title":"Custom development and integration","description":"Build systems, applications, and integrations, with AI assistance, automation, dashboards, and alerts as needed."},{"title":"Data and access design","description":"Integrate data sources and fields, and plan data governance, role-based access, activity records, and security."},{"title":"Rollout and support handover","description":"Plan testing, acceptance, deployment, backups, and operational handover. Agree source-code delivery, hosting, and ongoing support responsibilities."}], deliverables: ["Requirements analysis","Architecture map","Adoption roadmap"], execution: "Connects to custom development, integration, and delivery support." },
      { id: "digital-integration", shortLabel: "Digital Integration", title: "Digital Integration", summary: "Build brand websites, commerce, and membership features, connecting payments, logistics, and internal systems to everyday operations.", situations: ["Teams manually move data between tools","Web, payment, logistics, and internal systems operate separately"], scope: [{"title":"Brand and multilingual websites","description":"Plan content structure, pages, and management features for device compatibility, brand presentation, and routine updates."},{"title":"Commerce, membership, and booking","description":"Build agreed product, transaction, membership, or booking features, and define payment, notification, and downstream workflow integrations."},{"title":"Third-party and data integration","description":"Review payment, logistics, CRM, and ERP interfaces to define data exchange, update responsibilities, and exception handling."},{"title":"Workflow automation and handover","description":"Automate confirmed recurring work and plan integration testing, data migration, launch, and operational handover."}], deliverables: ["Integration map","Connection inventory","Prioritized plan"], execution: "Connects to web, commerce, membership, payments, logistics, and automation." },
      { id: "visual-design", shortLabel: "Visual Design", title: "Visual Design", summary: "Create brand identities, website and interface visuals, marketing assets, and guidelines for consistent presentation across customer touchpoints.", situations: ["Brand applications feel inconsistent","Digital interfaces lack visual hierarchy"], scope: [{"title":"Brand identity and applications","description":"Review an existing brand or define an identity direction, with agreed logos, colors, typography, and applications."},{"title":"Website and interface visuals","description":"Organize information hierarchy and usage needs to design pages, interfaces, and visual components."},{"title":"Marketing and print materials","description":"Create agreed social, advertising, presentation, catalog, and print layouts with confirmed dimensions and output specifications."},{"title":"Design guidelines and handover","description":"Document templates and asset usage, and agree editable files, export formats, and font and stock-image licensing."}], deliverables: ["Visual direction","Design guidelines","Improvement list"], execution: "Connects to identity, UI, web visuals, and campaign assets." },
      { id: "international-marketing", shortLabel: "International Marketing", title: "International Marketing", summary: "Plan positioning, multilingual content, search, and advertising for target markets, connecting websites and measurement to support international operations.", situations: ["Preparing to enter overseas markets","Multilingual content exists without a conversion path"], scope: [{"title":"Market and audience positioning","description":"Assess target markets against your product, customers, competition, and resources to define entry priorities and channel responsibilities."},{"title":"Multilingual content and search","description":"Plan localized content, search terms, and site structure, with agreed translation, local review, and ongoing update responsibilities."},{"title":"Campaign assets and advertising","description":"Produce agreed content and advertising assets and manage selected channels. Confirm account access, media budgets, and service fees separately."},{"title":"Measurement and improvement","description":"Define verifiable inquiry, conversion, or other operating metrics, with reporting and improvement recommendations. Results are assessed against market conditions."}], deliverables: ["Market-entry strategy","Content direction","Execution plan"], execution: "Connects to multilingual websites, SEO, advertising, and market execution." },
      { id: "international-finance", shortLabel: "International Finance", title: "International Finance", summary: "Combine information technology with cross-border legal, tax, and financial expertise to help businesses and families organize assets, assess transactions, and plan international operations using verifiable information.", situations: ["Planning international investment, funding introductions, or cross-border transactions","Assets held across jurisdictions require consolidated ownership and financial records","Family members have different nationalities or residences and need coordinated succession and trust planning","An investment or partnership requires background, funding, and exit-condition checks"], scope: [{"title":"Cross-border funding introductions","description":"define funding needs, connect professional resources, and coordinate terms"},{"title":"Cross-border asset inventory","description":"consolidate assets, liabilities, ownership structures, and supporting documents"},{"title":"Background research and proof-of-funds coordination","description":"review public and lawfully authorized information, funding evidence, and document authenticity"},{"title":"Tax and payment planning coordination","description":"connect legal, tax, and financial professionals to review reporting and transaction needs"},{"title":"Trust and succession coordination","description":"organize beneficiary arrangements, cross-border inheritance needs, and setup tasks"},{"title":"Cross-border corporate structures","description":"coordinate professional assessment of entities, ownership, and investment structures"},{"title":"Investment risk and exit assessment","description":"clarify transaction terms, fund flows, exit mechanisms, and unresolved risks"},{"title":"Family office and asset planning systems","description":"integrate asset records, documents, permissions, reporting, and collaboration"}], deliverables: ["Cross-border requirements, asset inventory, and ownership map","Background and funding documentation with items requiring verification","Professional responsibilities, planning topics, and implementation sequence","Transaction risks, exit conditions, and decision information checklist","Asset management and family office system blueprint"], execution: "ESTIGINTO provides information integration, system development, and professional coordination. Legal, tax, trust, and financial matters are assessed and implemented with relevant professional teams according to the requirements." },
    ],
  },
  ja: {
    sectionLabel: "ビジネスコンサルティング", sectionMeta: "5つの専門領域", intro: "ブランド基準、業務フロー、技術環境を確認し、各段階の目標、役割分担、実施の優先順位を整理します。",
    labels: { situations: "適した状況", scope: "支援範囲", deliverables: "成果物", execution: "実行支援", consult: "お問い合わせ" }, processTitle: "支援の流れ", process: ["現状整理", "目標確認", "戦略設計", "実行連携", "効果検証"],
    services: [
      { id: "systems-consulting", shortLabel: "情報システム", title: "情報システム", summary: "要件・業務の整理から個別開発まで、システム、データ、権限を統合し、日常業務と継続的な運用を支援します。", situations: ["ERP・CRM・WMS の導入や刷新","システムと業務が分断している"], scope: [{"title":"業務とシステムの計画","description":"現行業務、利用者の役割、既存ツールを確認し、機能要件、データの流れ、導入の優先順位を整理します。"},{"title":"個別開発とシステム連携","description":"システムやアプリの開発・連携に加え、AI支援、自動化、ダッシュボード、異常通知を計画します。"},{"title":"データと権限の設計","description":"データの出所と項目を統合し、データ管理、役割別の権限、アクセス記録、情報セキュリティの要件を整理します。"},{"title":"導入と運用引き継ぎ","description":"テスト、検収、配備、バックアップ、操作の引き継ぎを計画し、ソースコード、ホスティング、保守の範囲を合意します。"}], deliverables: ["要件分析","構成図","導入ロードマップ"], execution: "カスタム開発、既存連携、プロジェクト支援へ接続できます。" },
      { id: "digital-integration", shortLabel: "デジタル統合", title: "デジタル統合", summary: "ブランドサイト、EC、会員機能を構築し、決済、物流、社内システムと連携させ、Webと日常業務をつなぎます。", situations: ["ツール間の手作業が多い","決済・物流・社内システムが分断している"], scope: [{"title":"ブランド・多言語サイト","description":"内容構成、ページ、管理機能を計画し、端末対応、ブランド表現、日常の更新に配慮します。"},{"title":"EC・会員・予約機能","description":"商品、取引、会員、予約の機能を業務に合わせて構築し、決済、通知、後続業務の連携要件を整理します。"},{"title":"外部サービスとデータ連携","description":"決済、物流、CRM、ERPなどのインターフェースを確認し、データ交換、更新担当、例外処理を整理します。"},{"title":"業務自動化と引き継ぎ","description":"合意した反復業務を自動化し、統合テスト、データ移行、公開、操作の引き継ぎを計画します。"}], deliverables: ["統合構成図","連携一覧","優先順位"], execution: "Web、EC、会員、決済、物流、自動化の構築へ接続できます。" },
      { id: "visual-design", shortLabel: "ビジュアルデザイン", title: "ビジュアルデザイン", summary: "ブランド識別、Web・UIのビジュアル、販促素材、運用ガイドを制作し、各接点で一貫したブランド表現を整えます。", situations: ["ブランド表現が統一されていない","画面の情報階層が分かりにくい"], scope: [{"title":"ブランド識別と展開","description":"既存ブランドの確認や識別方針の計画を行い、合意したロゴ、色彩、書体、応用デザインを制作します。"},{"title":"WebとUIのビジュアル","description":"情報階層と利用場面を整理し、ページ、操作画面、コンポーネントの見た目を設計します。"},{"title":"販促・印刷素材","description":"SNS、広告、プレゼン資料、カタログ、印刷用レイアウトを制作し、寸法と出力仕様を確認します。"},{"title":"デザイン規定と引き継ぎ","description":"テンプレートや素材の利用方法を整理し、編集可能なファイル、出力形式、書体・画像のライセンス条件を合意します。"}], deliverables: ["ビジュアル方針","デザイン規定","改善一覧"], execution: "ブランド、UI、Web、マーケティング素材制作へ接続できます。" },
      { id: "international-marketing", shortLabel: "国際マーケティング", title: "国際マーケティング", summary: "対象市場に応じたブランドの位置づけ、多言語コンテンツ、検索・広告施策を計画し、Webサイトと効果測定を連携させます。", situations: ["海外市場への進出を検討している","多言語コンテンツに成果導線がない"], scope: [{"title":"市場と顧客の位置づけ","description":"製品、顧客、競争条件、投入可能な資源を基に対象市場を検討し、参入方針と販路の役割を整理します。"},{"title":"多言語コンテンツと検索","description":"現地向けコンテンツ、検索語、サイト構成を計画し、翻訳、現地確認、継続更新の担当を合意します。"},{"title":"販促素材と広告運用","description":"合意したコンテンツ・広告素材の制作とチャネル運用を行い、アカウント権限、広告予算、サービス費を分けて確認します。"},{"title":"効果測定と改善","description":"問い合わせ、成約など確認可能な指標を定め、レポートと改善提案を提供します。成果は市場条件を踏まえて評価します。"}], deliverables: ["市場参入戦略","コンテンツ方針","実行計画"], execution: "多言語サイト、SEO、広告、海外施策へ接続できます。" },
      { id: "international-finance", shortLabel: "国際金融", title: "国際金融", summary: "情報技術と国際的な法務・税務・金融の専門知識を組み合わせ、企業やご家族の資産整理、取引評価、海外展開を支援します。確認可能な情報に基づく意思決定を支えます。", situations: ["海外投資、資金調達先の紹介、国際取引を検討している","複数の国・地域にある資産の保有関係や財務情報を整理したい","家族の国籍や居住地が異なり、承継・信託の専門家連携が必要","投資や提携前に、相手方の背景、資金、出口条件を確認したい"], scope: [{"title":"国際的な資金調達先の紹介","description":"資金需要の整理、専門家との連携、条件の調整"},{"title":"国際資産の棚卸し","description":"資産・負債・保有構造・関連文書の整理"},{"title":"背景調査・資金証明の確認支援","description":"公開情報や適法に利用許諾を得た情報、資金証明、文書の真正性の確認"},{"title":"国際税務・資金移動の計画支援","description":"法務・税務・金融の専門家と申告・取引要件を整理"},{"title":"信託・承継計画の支援","description":"受益者の設定、国際相続の要件、設立手続きの整理"},{"title":"国際的な企業構造","description":"専門家と法人・持分・投資構造を検討"},{"title":"投資リスクと出口の評価","description":"取引条件、資金の流れ、出口の仕組み、未確認リスクを整理"},{"title":"ファミリーオフィス・資産計画システム","description":"資産情報、文書、権限、レポート、協働フローを統合"}], deliverables: ["国際案件の要件・資産一覧・保有関係図","背景調査・資金証明資料と要確認事項","専門家の役割分担・検討事項・実施順序","取引リスク・出口条件・意思決定情報の一覧","資産管理・ファミリーオフィスのシステム構築計画"], execution: "ESTIGINTO は情報統合、システム構築、専門家間の連携を担当します。法務・税務・信託・金融に関する事項は、要件に応じて関連する専門チームと評価・実施します。" },
    ],
  },
};
